### PR TITLE
LDAP fix and doc update

### PR DESCRIPTION
**Pull request by bersace**
cc @sgns12, #272

### CODE REVIEW

**Comment by bersace** [comment]
Ok, It's good now. I dropped outdated workarounds too.

**Comment by bersace** [comment]
Let's merge, I would like to rebase other branches on it.

**Comment by sgns12** [comment]
Just came back from vacation and see the issue is resolved.
glad to hear.
can you please let me know if i was doing something wrong?
it was working with one instance of ldap and was not working with another.
or may be my files were wrong?

P.S.
if i want to have ldap2pg just to add a new user it finds in ldap to ldap_roles and to someotherrole, w/o doing anything else , is it possible? 
tried to do that on minimal yml, but no luck
or if you prefer to open new issue, i will
thank you

**Comment by sgns12** [comment]
someotherrole is a role already defined in PG

**Comment by bersace** [comment]
@sgns12, the key part is to **split** role.

The bad solution, with conflict between ldap2pg and manual management:

```
rw_local -> user_from_ldap
```

This way, rw_local must be managed by ldap2pg, thus privileges not `granted` in YAML are dropped.

The good solution : separation of concern : one role for manual management, one role for ldap2pg:

```
rw_local -> rw_local_members -> user_from_ldap
```

You have to manually add rw_local_members as child of rw_local and exclude rw_local from ldap2pg.

**Comment by sgns12** [comment]
thank you so much for your help.
not sure if i can close this issue or you have 
looking how to close it

**Comment by bersace** [comment]
@sgns12 this is a PR, it's already merged. You can close #272

**Pull request merged**
