### PR TITLE
Case

### PR DESCRIPTION
**Pull request by bersace**
cf. #164 

@dirks this should fix the `unknown attribute`. Can you test master ?

### CODE REVIEW

**Comment by dirks** [comment]
@bersace thanks, I will test master tomorrow.

**Comment by dirks** [comment]
With master there is an error in ldap2pg.script, 4.1 runs normal with the same parameters. Here the error from the master run:

```
[ldap2pg.ldap        DEBUG] Doing: ldapsearch -x -D cn=mybinduser,ou=Functional Users,ou=Users,ou=IDIV,dc=idiv,dc=de -W -b ou=AAI,dc=idiv,dc=de -s sub '(memberOf:1.2.840.113556.1.4.1941:=cn=g_r_postgres01-KREINITZ_rw,ou=FunctionalGroups,ou=Groups,ou=IDIV,dc=idiv,dc=de)' 
[ldap2pg.script      ERROR] Unhandled error:
[ldap2pg.script      ERROR] Traceback (most recent call last):
[ldap2pg.script      ERROR]   File "/opt/python-ldap2pg-dev/lib/python2.7/site-packages/ldap2pg/script.py", line 80, in main
[ldap2pg.script      ERROR]     exit(wrapped_main(config))
[ldap2pg.script      ERROR]   File "/opt/python-ldap2pg-dev/lib/python2.7/site-packages/ldap2pg/script.py", line 59, in wrapped_main
[ldap2pg.script      ERROR]     sync_data = manager.inspect(syncmap=config['sync_map'])
[ldap2pg.script      ERROR]   File "/opt/python-ldap2pg-dev/lib/python2.7/site-packages/ldap2pg/manager.py", line 314, in inspect
[ldap2pg.script      ERROR]     ldaproles, ldapacls = self.inspect_ldap(syncmap)
[ldap2pg.script      ERROR]   File "/opt/python-ldap2pg-dev/lib/python2.7/site-packages/ldap2pg/manager.py", line 259, in inspect_ldap
[ldap2pg.script      ERROR]     entries = self.query_ldap(**mapping['ldap'])
[ldap2pg.script      ERROR]   File "/opt/python-ldap2pg-dev/lib/python2.7/site-packages/ldap2pg/manager.py", line 120, in query_ldap
[ldap2pg.script      ERROR]     base, scope, filter, attributes,
[ldap2pg.script      ERROR]   File "/opt/python-ldap2pg-dev/lib/python2.7/site-packages/ldap2pg/ldap.py", line 138, in search_s
[ldap2pg.script      ERROR]     return self.wrapped.search_s(base, scope, filter, attributes)
[ldap2pg.script      ERROR]   File "/opt/python-ldap2pg-dev/lib/python2.7/site-packages/ldap2pg/ldap.py", line 109, in __call__
[ldap2pg.script      ERROR]     return decode_value(self.callable_(*a, **kw))
[ldap2pg.script      ERROR]   File "/opt/python-ldap2pg-dev/lib/python2.7/site-packages/ldap2pg/utils.py", line 69, in decode_value
[ldap2pg.script      ERROR]     return [decode_value(v) for v in value]
[ldap2pg.script      ERROR]   File "/opt/python-ldap2pg-dev/lib/python2.7/site-packages/ldap2pg/utils.py", line 71, in decode_value
[ldap2pg.script      ERROR]     return tuple([decode_value(v) for v in value])
[ldap2pg.script      ERROR]   File "/opt/python-ldap2pg-dev/lib/python2.7/site-packages/ldap2pg/utils.py", line 66, in decode_value
[ldap2pg.script      ERROR]     for k, v in value.items()
[ldap2pg.script      ERROR]   File "/opt/python-ldap2pg-dev/lib/python2.7/site-packages/ldap2pg/utils.py", line 69, in decode_value
[ldap2pg.script      ERROR]     return [decode_value(v) for v in value]
[ldap2pg.script      ERROR]   File "/opt/python-ldap2pg-dev/lib/python2.7/site-packages/ldap2pg/utils.py", line 62, in decode_value
[ldap2pg.script      ERROR]     return value.decode('utf-8')
[ldap2pg.script      ERROR]   File "/opt/python-ldap2pg-dev/lib64/python2.7/encodings/utf_8.py", line 16, in decode
[ldap2pg.script      ERROR]     return codecs.utf_8_decode(input, errors, True)
[ldap2pg.script      ERROR] UnicodeDecodeError: 'utf8' codec can't decode byte 0xae in position 2: invalid start byte
[ldap2pg.script      ERROR] Please file an issue at https://github.com/dalibo/ldap2pg/issues with full log.
[ldap2pg.psql        DEBUG] Closing Postgres cursor to dbname=template1.
```

**Comment by bersace** [comment]
@dirks can you send me a raw value ? I'm wondering if you get some Windows encoding instead of UTF-8.

**Comment by bersace** [comment]
You can get raw value with something like:

``` console
$ DEBUG=1 ldap2pg ...
...
>>> input
'\xae...'
```

**Comment by dirks** [comment]
I tested it with a several different users in the group which give different raw values, e.g. for testuserdirk it is
```
'\x01\x05\x00\x00\x00\x00\x00\x05\x15\x00\x00\x00\xbd\x12~\xc8\xbd\x90n\xd2\xdc\xa2<\x11&\x18\x00\x00'
```
Let me know if you need additional attributes of the account.

**Comment by bersace** [comment]
@dirks wow. This looks like binary data like an image. `ldap2pg` should not query binary data. Do you know why there is no attributes in the `ldapsearch` command ?

**Comment by dirks** [comment]
The error was a typo in the configuration and some point I must have deleted a l in roles. I wonder why it did still work in 4.1 where it used samaccountname as attribute. Let me do a few more runs.

**Comment by bersace** [comment]
@dirks ok, maybe `ldap2pg` miss a check on configuration. Let me know if you find a configuration that `ldap2pg` should refuse before doing bad queries.

**Comment by dirks** [comment]
After some more tests using strange user and samaccountnames I would say the merge fixes #164

**Comment by bersace** [comment]
Let's release this. :-)

**Pull request merged**
