### PR TITLE
Warn about empty sync_map in manager

### PR DESCRIPTION
**Pull request by bersace**
Closes: #321

### CODE REVIEW

**Comment by bersace** [comment]
@guruguruguru Are you able to review it ?

**Comment by guruguruguru** [comment]
Hi @bersace ,

we have tested all use cases and it looks good except maybe:

`echo "blacklist: []"| ldap2pg -c -`

would give ldap2pg a config file without explicit sync_map and would empty the postgresql roles. Maybe you would like to prevent this as well as there is no sync_map configuration (not even an empty one) at all.

Everything else looks good to me.

Regards,
Dennis

**Comment by bersace** [comment]
Good catch, i'll fix this.

**Comment by bersace** [comment]
@guruguruguru ok, fixed.

**Comment by guruguruguru** [comment]
Hi @bersace 

this is great. Do you need me to do anything else?
And do you know who is maintaining the RPMs on the official postgres repos for ldap2pg?

Thanks a lot,
Dennis

**Comment by bersace** [comment]
>  And do you know who is maintaining the RPMs on the official postgres repos for ldap2pg?

It's https://twitter.com/DevrimGunduz/ . Need to release this. I'm going to wait for a few next changes before releasing. Is it ok for you ?

**Comment by guruguruguru** [comment]
Yes thats perfect! Thanks a lot!

**Pull request merged**
